const moviesActionTypes = {
  FETCH_NOW_PLAYING_MOVIES_START: "FETCH_NOW_PLAYING_MOVIES_START",
  FETCH_NOW_PLAYING_MOVIES_SUCCESS: "FETCH_NOW_PLAYING_MOVIES_SUCCESS",
  FETCH_NOW_PLAYING_MOVIES_FAIL: "FETCH_NOW_PLAYING_MOVIES_FAIL",

  FETCH_TOP_RATED_MOVIES_START: "FETCH_TOP_RATED_MOVIES_START",
  FETCH_TOP_RATED_MOVIES_SUCCESS: "FETCH_TOP_RATED_MOVIES_SUCCESS",
  FETCH_TOP_RATED_MOVIES_FAIL: "FETCH_TOP_RATED_MOVIES_FAIL",

  FETCH_POPULAR_MOVIES_START: "FETCH_POPULAR_MOVIES_START",
  FETCH_POPULAR_MOVIES_SUCCESS: "FETCH_POPULAR_MOVIES_SUCCESS",
  FETCH_POPULAR_MOVIES_FAIL: "FETCH_POPULAR_MOVIES_FAIL",

  FETCH_GENRES_START: "FETCH_GENRES_START",
  FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
  FETCH_GENRES_FAIL: "FETCH_GENRES_FAIL",

  FETCH_MOVIE_BY_ID_START: "FETCH_MOVIE_BY_ID_START",
  FETCH_MOVIE_BY_ID_SUCCESS: "FETCH_MOVIE_BY_ID_SUCCESS",
  FETCH_MOVIE_BY_ID_FAIL: "FETCH_MOVIE_BY_ID_FAIL",

  ADD_TO_WATCHLIST: "ADD_TO_WATCHLIST",
  REMOVE_FROM_WATCHLIST: "REMOVE_FROM_WATCHLIST",
};

export default moviesActionTypes;
